version: '3.8'

services:
  frontend:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host
    depends_on:
      - app

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_NAME=horsetooth_liquidators
      - JWT_SECRET=your_jwt_secret
      - CORS_ORIGIN=http://localhost:5173
      - PORT=3000
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: horsetooth_liquidators
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 