version: '3.8'

services:
  frontend:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    command: npm run dev -- --host
    depends_on:
      - app

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_NAME=horsetooth_liquidators
      - JWT_SECRET=your_jwt_secret
      - CORS_ORIGIN=http://localhost:5173
      - PORT=8080
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=your_password pg_isready -h db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: horsetooth_liquidators
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 